# Browser config
browser:
  default: remote #chrome, firefox, edge, remote (Docker needs to be installed locally)
  maximize: true #true, false
  seeVNC: true #true, false --> only applicable for remote --> this allows to open a browser and see the test
  mobile: false #true, false
  headless: false #true, false
  tearDown: true #true, false
screenshots:
  format: .png

# This file is meant to be used with the YML helper. End of file